# Known Issues, Bugs and Common Errors{- #knownissues}

## Overview {-}

This is a list of issues that are known and that we are working on to fix. 

If you discover another issue that is not listed here you can report the issue [here](https://github.com/RebeccaJLai/exp_manual/issues)- but please check that it has not been reported before you open another issue for it.

## Common Errors {-}

### Data not being saved despite questions being completed.

If you use HTML tags, you must ensure that you have matching opening and closing tags. Unmatched tags will prevent data from being recorded from this component.

## Issues... {-}

### Which do NOT interfere with the operation of the site {-}

These issues are bugs which do not prevent the intended function of the action being carried out at the time of their occurrance and are considered to be of low priority.

#### "The supervisor or supervised could not be found" when changing account type  {- #notfound}

This happens when a supervisor attempts to change the account type of a student from "registered" to "student". The account changes are carried out regardless of the message. 

To check this log out, log back in and then check the status of the student. 

```{block, type = "info"}
The account being changed must log out and then back in for any changes to take effect, regardless of whether you experience this bug or not.
```

### Which DO interfere with the operation of the site {-}

These issues are bugs which in some way inhibit the function of the site and are considered high priority for fixes and workarounds.

#### Email Notifications {-}

Email notifications are not always sent. 

E-mails notifying students and supervisors of changes of account type work seemingly without issue. In particular, e-mails requesting supervisors turn studies to "active" are not being sent.

```{block, type = "workaround"}
**Workaround:** Please e-mail your supervisor directly if you require them to review and activate your study.
```

#### Cannot Share Ownership of Components With Students {-}

At the moment it is not possible to share components with students. This stems from a work-around regarding access to and protection of data. Anyone who is an owner of a component may download the data gathered by it, even if that component is also used by others.

```{block, type = "workaround"}
**Workaround:** At the moment it is recommended that students create their own components to suit their needs or that the supervisor create any regularly used components, duplicate them and assign the duplicate to the student in need.

If you are using questionnaires you may want to consider creating a spreadsheet with the questions, following the templates discussed in the section about [adding questions in bulk](#addfromspreadsheet).
```

#### One of (equal) preventing sets from running {- #oneofequal}

The "one of (equal)" randomisation. There has been a report of this preventing the set from working. On testing no items in the set were run, and no items shown in the "test" sampling of assignment to items in the set. 

```{block, type = "workaround"}
Unless there is a *strong theoretical basis* for attempting to recruit equal numbers of men and women into each item within a set it is suggested that you use "one of (random)".

If you need to recruit specific number of individuals into each item (where gender identification is not theoretically relevant) we recommend that you monitor the number of completions and work with your supervisor and admins to turn off specific components when the required number is reached.
```

